/** This file is generated by Better Convex Nuxt. Do not edit. */
import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export const tables = {
  user: defineTable({
    id: v.string(),
    name: v.string(),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.union(v.null(), v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    twoFactorEnabled: v.union(v.null(), v.boolean()),
    bcnSecurityGeneration: v.number(),
  })
    .index('id', ['id'])
    .index('name', ['name'])
    .index('email', ['email'])
    .index('createdAt', ['createdAt']),
  session: defineTable({
    id: v.string(),
    expiresAt: v.number(),
    token: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    ipAddress: v.union(v.null(), v.string()),
    userAgent: v.union(v.null(), v.string()),
    userId: v.string(),
    bcnAssuranceGeneration: v.number(),
    bcnAssuranceMethod: v.string(),
    bcnAuthenticatedAt: v.number(),
    bcnSessionStartedAt: v.number(),
  })
    .index('id', ['id'])
    .index('expiresAt', ['expiresAt'])
    .index('userId_expiresAt', ['userId', 'expiresAt'])
    .index('token', ['token'])
    .index('createdAt', ['createdAt'])
    .index('userId', ['userId']),
  account: defineTable({
    id: v.string(),
    issuer: v.string(),
    accountId: v.string(),
    providerId: v.string(),
    userId: v.string(),
    accessToken: v.union(v.null(), v.string()),
    refreshToken: v.union(v.null(), v.string()),
    idToken: v.union(v.null(), v.string()),
    accessTokenExpiresAt: v.union(v.null(), v.number()),
    refreshTokenExpiresAt: v.union(v.null(), v.number()),
    scope: v.union(v.null(), v.string()),
    password: v.union(v.null(), v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('id', ['id'])
    .index('issuer_accountId', ['issuer', 'accountId'])
    .index('userId', ['userId'])
    .index('createdAt', ['createdAt']),
  verification: defineTable({
    id: v.string(),
    identifier: v.string(),
    value: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
    bcnAssuranceGeneration: v.union(v.null(), v.number()),
  })
    .index('id', ['id'])
    .index('expiresAt', ['expiresAt'])
    .index('identifier', ['identifier'])
    .index('identifier_createdAt', ['identifier', 'createdAt'])
    .index('createdAt', ['createdAt']),
  twoFactor: defineTable({
    id: v.string(),
    secret: v.string(),
    backupCodes: v.string(),
    userId: v.string(),
    verified: v.union(v.null(), v.boolean()),
    failedVerificationCount: v.union(v.null(), v.number()),
    lockedUntil: v.union(v.null(), v.number()),
    bcnPendingSecret: v.union(v.null(), v.string()),
    bcnPendingBackupCodes: v.union(v.null(), v.string()),
    bcnPendingSessionId: v.union(v.null(), v.string()),
    bcnPendingGeneration: v.union(v.null(), v.number()),
  })
    .index('id', ['id'])
    .index('secret', ['secret'])
    .index('userId', ['userId']),
} as const

const schema = defineSchema(tables)
Object.defineProperty(schema, '__betterConvexNuxtAuthSchemaFingerprint', {
  value: 'bcn-auth-schema-v2:7b8c0a08e31d1fdb',
})

export default schema
