/** This file is generated by Better Convex Nuxt. Do not edit. */
// prettier-ignore
const schemaMetadata = {
  "fingerprint": "bcn-auth-schema-v2:7254f64c808079d6",
  "models": {
    "user": {
      "logicalName": "user",
      "physicalName": "user",
      "fields": {
        "id": {
          "logicalName": "id",
          "physicalName": "id",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": true,
          "updatable": false
        },
        "name": {
          "logicalName": "name",
          "physicalName": "name",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": true,
          "unique": false,
          "updatable": true
        },
        "email": {
          "logicalName": "email",
          "physicalName": "email",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": true,
          "unique": true,
          "updatable": true
        },
        "emailVerified": {
          "logicalName": "emailVerified",
          "physicalName": "emailVerified",
          "kind": "boolean",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "image": {
          "logicalName": "image",
          "physicalName": "image",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "createdAt": {
          "logicalName": "createdAt",
          "physicalName": "createdAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "updatedAt": {
          "logicalName": "updatedAt",
          "physicalName": "updatedAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "isAnonymous": {
          "logicalName": "isAnonymous",
          "physicalName": "isAnonymous",
          "kind": "boolean",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "bcnSecurityGeneration": {
          "logicalName": "bcnSecurityGeneration",
          "physicalName": "bcnSecurityGeneration",
          "kind": "number",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        }
      },
      "indexes": [
        {
          "descriptor": "id",
          "fields": [
            "id"
          ],
          "unique": true
        },
        {
          "descriptor": "name",
          "fields": [
            "name"
          ]
        },
        {
          "descriptor": "email",
          "fields": [
            "email"
          ],
          "unique": true
        },
        {
          "descriptor": "createdAt",
          "fields": [
            "createdAt"
          ]
        }
      ]
    },
    "session": {
      "logicalName": "session",
      "physicalName": "session",
      "fields": {
        "id": {
          "logicalName": "id",
          "physicalName": "id",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": true,
          "updatable": false
        },
        "expiresAt": {
          "logicalName": "expiresAt",
          "physicalName": "expiresAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "token": {
          "logicalName": "token",
          "physicalName": "token",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": true,
          "updatable": true
        },
        "createdAt": {
          "logicalName": "createdAt",
          "physicalName": "createdAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "updatedAt": {
          "logicalName": "updatedAt",
          "physicalName": "updatedAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "ipAddress": {
          "logicalName": "ipAddress",
          "physicalName": "ipAddress",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "userAgent": {
          "logicalName": "userAgent",
          "physicalName": "userAgent",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "userId": {
          "logicalName": "userId",
          "physicalName": "userId",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": false,
          "updatable": true,
          "reference": {
            "model": "user",
            "field": "id",
            "onDelete": "cascade"
          }
        },
        "bcnAssuranceGeneration": {
          "logicalName": "bcnAssuranceGeneration",
          "physicalName": "bcnAssuranceGeneration",
          "kind": "number",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        }
      },
      "indexes": [
        {
          "descriptor": "id",
          "fields": [
            "id"
          ],
          "unique": true
        },
        {
          "descriptor": "expiresAt",
          "fields": [
            "expiresAt"
          ]
        },
        {
          "descriptor": "userId_expiresAt",
          "fields": [
            "userId",
            "expiresAt"
          ]
        },
        {
          "descriptor": "token",
          "fields": [
            "token"
          ],
          "unique": true
        },
        {
          "descriptor": "createdAt",
          "fields": [
            "createdAt"
          ]
        },
        {
          "descriptor": "userId",
          "fields": [
            "userId"
          ]
        }
      ]
    },
    "account": {
      "logicalName": "account",
      "physicalName": "account",
      "fields": {
        "id": {
          "logicalName": "id",
          "physicalName": "id",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": true,
          "updatable": false
        },
        "accountId": {
          "logicalName": "accountId",
          "physicalName": "accountId",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "providerId": {
          "logicalName": "providerId",
          "physicalName": "providerId",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "userId": {
          "logicalName": "userId",
          "physicalName": "userId",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": false,
          "updatable": true,
          "reference": {
            "model": "user",
            "field": "id",
            "onDelete": "cascade"
          }
        },
        "accessToken": {
          "logicalName": "accessToken",
          "physicalName": "accessToken",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "refreshToken": {
          "logicalName": "refreshToken",
          "physicalName": "refreshToken",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "idToken": {
          "logicalName": "idToken",
          "physicalName": "idToken",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "accessTokenExpiresAt": {
          "logicalName": "accessTokenExpiresAt",
          "physicalName": "accessTokenExpiresAt",
          "kind": "date",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "refreshTokenExpiresAt": {
          "logicalName": "refreshTokenExpiresAt",
          "physicalName": "refreshTokenExpiresAt",
          "kind": "date",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "scope": {
          "logicalName": "scope",
          "physicalName": "scope",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "password": {
          "logicalName": "password",
          "physicalName": "password",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "createdAt": {
          "logicalName": "createdAt",
          "physicalName": "createdAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "updatedAt": {
          "logicalName": "updatedAt",
          "physicalName": "updatedAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        }
      },
      "indexes": [
        {
          "descriptor": "id",
          "fields": [
            "id"
          ],
          "unique": true
        },
        {
          "descriptor": "providerId_accountId",
          "fields": [
            "providerId",
            "accountId"
          ],
          "unique": true
        },
        {
          "descriptor": "userId",
          "fields": [
            "userId"
          ]
        },
        {
          "descriptor": "createdAt",
          "fields": [
            "createdAt"
          ]
        }
      ],
      "legacyFields": {
        "issuer": "string"
      }
    },
    "verification": {
      "logicalName": "verification",
      "physicalName": "verification",
      "fields": {
        "id": {
          "logicalName": "id",
          "physicalName": "id",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": true,
          "updatable": false
        },
        "identifier": {
          "logicalName": "identifier",
          "physicalName": "identifier",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "value": {
          "logicalName": "value",
          "physicalName": "value",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "expiresAt": {
          "logicalName": "expiresAt",
          "physicalName": "expiresAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "createdAt": {
          "logicalName": "createdAt",
          "physicalName": "createdAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "updatedAt": {
          "logicalName": "updatedAt",
          "physicalName": "updatedAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        }
      },
      "indexes": [
        {
          "descriptor": "id",
          "fields": [
            "id"
          ],
          "unique": true
        },
        {
          "descriptor": "expiresAt",
          "fields": [
            "expiresAt"
          ]
        },
        {
          "descriptor": "identifier",
          "fields": [
            "identifier"
          ]
        },
        {
          "descriptor": "identifier_createdAt",
          "fields": [
            "identifier",
            "createdAt"
          ]
        },
        {
          "descriptor": "createdAt",
          "fields": [
            "createdAt"
          ]
        }
      ]
    },
    "jwks": {
      "logicalName": "jwks",
      "physicalName": "jwks",
      "fields": {
        "id": {
          "logicalName": "id",
          "physicalName": "id",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": true,
          "updatable": false
        },
        "publicKey": {
          "logicalName": "publicKey",
          "physicalName": "publicKey",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "privateKey": {
          "logicalName": "privateKey",
          "physicalName": "privateKey",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "createdAt": {
          "logicalName": "createdAt",
          "physicalName": "createdAt",
          "kind": "date",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "expiresAt": {
          "logicalName": "expiresAt",
          "physicalName": "expiresAt",
          "kind": "date",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "alg": {
          "logicalName": "alg",
          "physicalName": "alg",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "crv": {
          "logicalName": "crv",
          "physicalName": "crv",
          "kind": "string",
          "nullable": true,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        }
      },
      "indexes": [
        {
          "descriptor": "id",
          "fields": [
            "id"
          ],
          "unique": true
        },
        {
          "descriptor": "createdAt",
          "fields": [
            "createdAt"
          ]
        }
      ]
    },
    "rateLimit": {
      "logicalName": "rateLimit",
      "physicalName": "rateLimit",
      "fields": {
        "id": {
          "logicalName": "id",
          "physicalName": "id",
          "kind": "string",
          "nullable": false,
          "indexed": true,
          "sortable": false,
          "unique": true,
          "updatable": false
        },
        "key": {
          "logicalName": "key",
          "physicalName": "key",
          "kind": "string",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": true,
          "updatable": true
        },
        "count": {
          "logicalName": "count",
          "physicalName": "count",
          "kind": "number",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        },
        "lastRequest": {
          "logicalName": "lastRequest",
          "physicalName": "lastRequest",
          "kind": "number",
          "nullable": false,
          "indexed": false,
          "sortable": false,
          "unique": false,
          "updatable": true
        }
      },
      "indexes": [
        {
          "descriptor": "id",
          "fields": [
            "id"
          ],
          "unique": true
        },
        {
          "descriptor": "key",
          "fields": [
            "key"
          ],
          "unique": true
        },
        {
          "descriptor": "lastRequest",
          "fields": [
            "lastRequest"
          ]
        }
      ]
    }
  }
} as const

export default schemaMetadata
